/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CircusWorld;
import Controller.EasyLevel;
import Controller.HardLevel;
import Controller.ModerateLevel;
import eg.edu.alexu.csd.oop.game.GameEngine;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Arwa Mohamed
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hardButton = new javax.swing.JButton();
        easyButton = new javax.swing.JButton();
        moderateButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(540, 250));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        hardButton.setBackground(new java.awt.Color(255, 204, 0));
        hardButton.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        hardButton.setForeground(new java.awt.Color(153, 0, 0));
        hardButton.setText("HARD");
        hardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hardButtonActionPerformed(evt);
            }
        });
        getContentPane().add(hardButton);
        hardButton.setBounds(130, 350, 250, 85);

        easyButton.setBackground(new java.awt.Color(255, 204, 0));
        easyButton.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        easyButton.setForeground(new java.awt.Color(153, 0, 0));
        easyButton.setText("EASY");
        easyButton.setBorderPainted(false);
        easyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                easyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(easyButton);
        easyButton.setBounds(90, 130, 320, 85);

        moderateButton.setBackground(new java.awt.Color(255, 204, 0));
        moderateButton.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        moderateButton.setForeground(new java.awt.Color(153, 0, 0));
        moderateButton.setText("MODERATE");
        moderateButton.setBorderPainted(false);
        moderateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moderateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(moderateButton);
        moderateButton.setBounds(90, 240, 320, 85);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\term 5\\programming 2\\lab\\Final\\Resources\\first.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 500, 580);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        MainFrame frame = new MainFrame();
        frame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formWindowClosing

    private void hardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hardButtonActionPerformed
        JMenuBar menuBar = new JMenuBar();
        JMenu menu = new JMenu("File");
        JMenuItem newMenuItem = new JMenuItem("New");
        JMenuItem pauseMenuItem = new JMenuItem("Pause");
        JMenuItem resumeMenuItem = new JMenuItem("Resume");
        menu.add(newMenuItem);
        menu.addSeparator();
        menu.add(pauseMenuItem);
        menu.add(resumeMenuItem);
        menuBar.add(menu);
        final GameEngine.GameController gameController = GameEngine.start("Hello", new CircusWorld(1250, 750, new HardLevel()), menuBar, Color.white);
        JFrame gameFrame = (JFrame) menuBar.getParent().getParent().getParent();
        gameFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        gameFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                if (JOptionPane.showConfirmDialog(gameFrame, "Are you sure you want to close this game?",
                        "End Game?", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                    gameFrame.dispose();
                    MainFrame newFrame = new MainFrame();
                    newFrame.setVisible(true);
                    newFrame.setSize(502, 574);

                    //some code to return to game main window.
                }
            }
        });
        newMenuItem.addActionListener((ActionEvent e) -> {
            gameController.changeWorld(new CircusWorld(1250, 750, new HardLevel()));
        });
        pauseMenuItem.addActionListener((ActionEvent e) -> {
            gameController.pause();
        });
        resumeMenuItem.addActionListener((ActionEvent e) -> {
            gameController.resume();
        });

        this.setVisible(false);
    }//GEN-LAST:event_hardButtonActionPerformed

    private void moderateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moderateButtonActionPerformed
        JMenuBar menuBar = new JMenuBar();
        JMenu menu = new JMenu("File");
        JMenuItem newMenuItem = new JMenuItem("New");
        JMenuItem pauseMenuItem = new JMenuItem("Pause");
        JMenuItem resumeMenuItem = new JMenuItem("Resume");
        menu.add(newMenuItem);
        menu.addSeparator();
        menu.add(pauseMenuItem);
        menu.add(resumeMenuItem);
        menuBar.add(menu);
        final GameEngine.GameController gameController = GameEngine.start("Hello", new CircusWorld(1250, 750, new ModerateLevel()), menuBar, Color.white);
        JFrame gameFrame = (JFrame) menuBar.getParent().getParent().getParent();
        gameFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        gameFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                if (JOptionPane.showConfirmDialog(gameFrame, "Are you sure you want to close this game?",
                        "End Game?", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                    gameFrame.dispose();
                    MainFrame newFrame = new MainFrame();
                    newFrame.setVisible(true);
                    newFrame.setSize(502, 574);
                    //some code to return to game main window.
                }
            }
        });
        newMenuItem.addActionListener((ActionEvent e) -> {
            gameController.changeWorld(new CircusWorld(1250, 750, new ModerateLevel()));
        });
        pauseMenuItem.addActionListener((ActionEvent e) -> {
            gameController.pause();
        });
        resumeMenuItem.addActionListener((ActionEvent e) -> {
            gameController.resume();
        });
        this.setVisible(false);
    }//GEN-LAST:event_moderateButtonActionPerformed

    private void easyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_easyButtonActionPerformed
        JMenuBar menuBar = new JMenuBar();
        JMenu menu = new JMenu("File");
        JMenuItem newMenuItem = new JMenuItem("New");
        JMenuItem pauseMenuItem = new JMenuItem("Pause");
        JMenuItem resumeMenuItem = new JMenuItem("Resume");
        menu.add(newMenuItem);
        menu.addSeparator();
        menu.add(pauseMenuItem);
        menu.add(resumeMenuItem);
        menuBar.add(menu);
        final GameEngine.GameController gameController = GameEngine.start("Hello", new CircusWorld(1250, 750, new EasyLevel()), menuBar, Color.white);
        JFrame gameFrame = (JFrame) menuBar.getParent().getParent().getParent();
        gameFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        gameFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                if (JOptionPane.showConfirmDialog(gameFrame, "Are you sure you want to close this game?",
                        "End Game?", JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {

                    gameFrame.dispose();
                    MainFrame newFrame = new MainFrame();
                    newFrame.setVisible(true);
                    newFrame.setSize(502, 574);
                    //some code to return to game main window.
                }
            }
        });
        newMenuItem.addActionListener((ActionEvent e) -> {
            gameController.changeWorld(new CircusWorld(1250, 750, new EasyLevel()));
        });
        pauseMenuItem.addActionListener((ActionEvent e) -> {
            gameController.pause();
        });
        resumeMenuItem.addActionListener((ActionEvent e) -> {
            gameController.resume();
        });
        this.setVisible(false);
    }//GEN-LAST:event_easyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame x = new MainFrame();
                x.setVisible(true);
                x.setSize(502, 574);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton easyButton;
    private javax.swing.JButton hardButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton moderateButton;
    // End of variables declaration//GEN-END:variables
}
